export interface Pharmacie {
    nom: string;
    photo: string;
    ville: string;
    prefecture: string;
    pays:string;
    contact_1: string;
    contact_2: string;
    email: string;
    adresse: string;
    latitude: string;
    longitude: string;
    map_link: string;
}

export const pharmaciesData: Pharmacie[] = [
    {
        "nom": "Pharmacie AM",
        "photo": "pharmacie-am.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 90 07 21 31",
        "contact_2": "+228 22 21 45 36",
        "email": "pharmaam@gmail.com",
        "adresse": "Rue Amoutivé, face école catholique Sacré Coeur",
        "latitude": "6.1351",
        "longitude": "1.2150",
        "map_link": "https://maps.google.com/?q=6.1351,1.2150"
    },
    {
        "nom": "Pharmacie BISSING",
        "photo": "pharmacie-bissing.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 90 05 77 85",
        "contact_2": "+228 22 21 36 45",
        "email": "pharmabissing@yahoo.fr",
        "adresse": "Rue de l'OCAM, face Lycée BONNECARRERE",
        "latitude": "6.1325",
        "longitude": "1.2132",
        "map_link": "https://maps.google.com/?q=6.1325,1.2132"
    },
    {
        "nom": "Pharmacie BLEUE",
        "photo": "pharmacie-bleue.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 90 20 04 50",
        "contact_2": "+228 22 22 50 50",
        "email": "pharmaciebleuetg@gmail.com",
        "adresse": "Carrefour Légèreté",
        "latitude": "6.1402",
        "longitude": "1.2201",
        "map_link": "https://maps.google.com/?q=6.1402,1.2201"
    },
    {
        "nom": "Pharmacie BON SECOURS",
        "photo": "pharmacie-bon-secours.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 90 05 05 05",
        "contact_2": "+228 22 21 05 05",
        "email": "pharmabonsecours@outlook.com",
        "adresse": "Avenue de la Paix, Tokoin Casablanca",
        "latitude": "6.1450",
        "longitude": "1.2250",
        "map_link": "https://maps.google.com/?q=6.1450,1.2250"
    },
    {
        "nom": "Pharmacie CIMTOGO",
        "photo": "pharmacie-cimtogo.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 90 00 00 61",
        "contact_2": "+228 22 21 00 61",
        "email": "pharmacimtogo@yahoo.fr",
        "adresse": "Route d'Aného, face usine CIMTOGO",
        "latitude": "6.1501",
        "longitude": "1.2302",
        "map_link": "https://maps.google.com/?q=6.1501,1.2302"
    },
    {
        "nom": "Pharmacie DA SILVA",
        "photo": "pharmacie-da-silva.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 90 05 25 35",
        "contact_2": "+228 22 21 25 35",
        "email": "pharmadasilva@gmail.com",
        "adresse": "Avenue de la Présidence, Bè Klikamé",
        "latitude": "6.1280",
        "longitude": "1.2105",
        "map_link": "https://maps.google.com/?q=6.1280,1.2105"
    },
    {
        "nom": "Pharmacie DE LA PAIX",
        "photo": "pharmacie-de-la-paix.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 90 08 18 28",
        "contact_2": "+228 22 21 18 28",
        "email": "pharmapaix@outlook.com",
        "adresse": "Carrefour Agbalépédogan",
        "latitude": "6.1420",
        "longitude": "1.2220",
        "map_link": "https://maps.google.com/?q=6.1420,1.2220"
    },
    {
        "nom": "Pharmacie DE L'ESPOIR",
        "photo": "pharmacie-de-l-espoir.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 90 09 19 29",
        "contact_2": "+228 22 21 19 29",
        "email": "pharmaespoir@yahoo.fr",
        "adresse": "Agoè Nyivé, près du marché",
        "latitude": "6.1550",
        "longitude": "1.2350",
        "map_link": "https://maps.google.com/?q=6.1550,1.2350"
    },
    {
        "nom": "Pharmacie DE L'UNION",
        "photo": "pharmacie-de-l-union.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 90 07 27 37",
        "contact_2": "+228 22 21 27 37",
        "email": "pharmaunion@gmail.com",
        "adresse": "Bè Kpota, face école primaire",
        "latitude": "6.1250",
        "longitude": "1.2080",
        "map_link": "https://maps.google.com/?q=6.1250,1.2080"
    },
    {
        "nom": "Pharmacie DU CENTRE",
        "photo": "pharmacie-du-centre.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 90 06 16 26",
        "contact_2": "+228 22 21 16 26",
        "email": "pharmacentre@outlook.com",
        "adresse": "Rue du Commerce, centre-ville",
        "latitude": "6.1304",
        "longitude": "1.2158",
        "map_link": "https://maps.google.com/?q=6.1304,1.2158"
    },
    {
        "nom": "Pharmacie DU MARCHE",
        "photo": "pharmacie-du-marche.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 90 04 14 24",
        "contact_2": "+228 22 21 14 24",
        "email": "pharmamarche@yahoo.fr",
        "adresse": "Grand Marché de Lomé",
        "latitude": "6.1285",
        "longitude": "1.2120",
        "map_link": "https://maps.google.com/?q=6.1285,1.2120"
    },
    {
        "nom": "Pharmacie ECO",
        "photo": "pharmacie-eco.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 90 03 13 23",
        "contact_2": "+228 22 21 13 23",
        "email": "pharmaeco@gmail.com",
        "adresse": "Agoè Logopé, carrefour ECOBANK",
        "latitude": "6.1480",
        "longitude": "1.2280",
        "map_link": "https://maps.google.com/?q=6.1480,1.2280"
    },
    {
        "nom": "Pharmacie HEBDO",
        "photo": "pharmacie-hebdo.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 90 02 12 22",
        "contact_2": "+228 22 21 12 22",
        "email": "pharmahebdo@outlook.com",
        "adresse": "Tokoin Solidarité, près de l'hôpital",
        "latitude": "6.1380",
        "longitude": "1.2180",
        "map_link": "https://maps.google.com/?q=6.1380,1.2180"
    },
    {
        "nom": "Pharmacie LA CONCORDE",
        "photo": "pharmacie-la-concorde.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 90 01 11 21",
        "contact_2": "+228 22 21 11 21",
        "email": "pharmaconcorde@yahoo.fr",
        "adresse": "Avenue de la Kozah, Nyékonakpoè",
        "latitude": "6.1350",
        "longitude": "1.2160",
        "map_link": "https://maps.google.com/?q=6.1350,1.2160"
    },
    {
        "nom": "Pharmacie LE BON PASTEUR",
        "photo": "pharmacie-le-bon-pasteur.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 90 00 10 20",
        "contact_2": "+228 22 21 10 20",
        "email": "pharmapasteur@gmail.com",
        "adresse": "Bè Château, derrière église catholique",
        "latitude": "6.1220",
        "longitude": "1.2050",
        "map_link": "https://maps.google.com/?q=6.1220,1.2050"
    },
    {
        "nom": "Pharmacie LES PERLES",
        "photo": "pharmacie-les-perles.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 90 09 29 39",
        "contact_2": "+228 22 21 29 39",
        "email": "pharmaperles@outlook.com",
        "adresse": "Agoè Centre, face station Total",
        "latitude": "6.1520",
        "longitude": "1.2320",
        "map_link": "https://maps.google.com/?q=6.1520,1.2320"
    },
    {
        "nom": "Pharmacie MODERNE",
        "photo": "pharmacie-moderne.jpg",
        "ville": "Kara",
        "prefecture": "Kozah",
        "pays": "Togo",
        "contact_1": "+228 90 08 28 38",
        "contact_2": "+228 23 45 67 89",
        "email": "pharmamoderne@yahoo.fr",
        "adresse": "Avenue du Marché, Kara centre",
        "latitude": "9.5483",
        "longitude": "1.1914",
        "map_link": "https://maps.google.com/?q=9.5483,1.1914"
    },
    {
        "nom": "Pharmacie NOTRE DAME",
        "photo": "pharmacie-notre-dame.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 90 07 37 47",
        "contact_2": "+228 22 21 37 47",
        "email": "pharmanotredame@gmail.com",
        "adresse": "Agoè Nyivé, près église Notre Dame",
        "latitude": "6.1570",
        "longitude": "1.2370",
        "map_link": "https://maps.google.com/?q=6.1570,1.2370"
    },
    {
        "nom": "Pharmacie SAINT JOSEPH",
        "photo": "pharmacie-saint-joseph.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 90 06 36 46",
        "contact_2": "+228 22 21 36 46",
        "email": "pharmasaintjoseph@outlook.com",
        "adresse": "Tokoin Ouest, près du collège Saint Joseph",
        "latitude": "6.1400",
        "longitude": "1.2200",
        "map_link": "https://maps.google.com/?q=6.1400,1.2200"
    },
    {
        "nom": "Pharmacie SAINT MICHEL",
        "photo": "pharmacie-saint-michel.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 90 05 35 45",
        "contact_2": "+228 22 21 35 45",
        "email": "pharmasaintmichel@yahoo.fr",
        "adresse": "Bè Est, face école Saint Michel",
        "latitude": "6.1180",
        "longitude": "1.2020",
        "map_link": "https://maps.google.com/?q=6.1180,1.2020"
    },
    {
        "nom": "Pharmacie SALAMA",
        "photo": "pharmacie-salama.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 90 04 34 44",
        "contact_2": "+228 22 21 34 44",
        "email": "pharmasalama@gmail.com",
        "adresse": "Agoè Assiyéyé, carrefour principal",
        "latitude": "6.1600",
        "longitude": "1.2400",
        "map_link": "https://maps.google.com/?q=6.1600,1.2400"
    },
    {
        "nom": "Pharmacie SANI",
        "photo": "pharmacie-sani.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 90 03 33 43",
        "contact_2": "+228 22 21 33 43",
        "email": "pharmasani@outlook.com",
        "adresse": "Adidogomé, marché Adidogomé",
        "latitude": "6.1450",
        "longitude": "1.2250",
        "map_link": "https://maps.google.com/?q=6.1450,1.2250"
    },
    {
        "nom": "Pharmacie SANTE PLUS",
        "photo": "pharmacie-sante-plus.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 90 02 32 42",
        "contact_2": "+228 22 21 32 42",
        "email": "pharmasanteplus@yahoo.fr",
        "adresse": "Légèreté, près du centre de santé",
        "latitude": "6.1420",
        "longitude": "1.2220",
        "map_link": "https://maps.google.com/?q=6.1420,1.2220"
    },
    {
        "nom": "Pharmacie SOLIDARITE",
        "photo": "pharmacie-solidarite.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 90 01 31 41",
        "contact_2": "+228 22 21 31 41",
        "email": "pharmasolidarite@gmail.com",
        "adresse": "Tokoin Solidarité, face mosquée",
        "latitude": "6.1380",
        "longitude": "1.2180",
        "map_link": "https://maps.google.com/?q=6.1380,1.2180"
    },
    {
        "nom": "Pharmacie SOS",
        "photo": "pharmacie-sos.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 90 00 30 40",
        "contact_2": "+228 22 21 30 40",
        "email": "pharmasos@outlook.com",
        "adresse": "Agoè Cacavéli, près clinique SOS",
        "latitude": "6.1500",
        "longitude": "1.2300",
        "map_link": "https://maps.google.com/?q=6.1500,1.2300"
    },
    {
        "nom": "Pharmacie VIE CLAIRE",
        "photo": "pharmacie-vie-claire.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 90 09 39 49",
        "contact_2": "+228 22 21 39 49",
        "email": "pharmavieclaire@yahoo.fr",
        "adresse": "Agoè Nyivé, route de Kpalimé",
        "latitude": "6.1550",
        "longitude": "1.2350",
        "map_link": "https://maps.google.com/?q=6.1550,1.2350"
    },
    {
        "nom": "Pharmacie Adidogomé",
        "photo": "pharmacie-adidogome.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 22 51 18 91",
        "contact_2": "",
        "email": "pharmacieadidogome@gmail.com",
        "adresse": "55R9+M95, Rue Adido, Lomé, Togo",
        "latitude": "6.1851679",
        "longitude": "1.1661428",
        "map_link": "https://maps.google.com/?q=6.1851679,1.1661428"
    },
    {
        "nom": "Pharmacie Actuelle",
        "photo": "pharmacie-actuelle.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 99 85 24 90",
        "contact_2": "",
        "email": "pharmacieactuelle@outlook.com",
        "adresse": "Lomé, Togo",
        "latitude": "6.1926012",
        "longitude": "1.1440171",
        "map_link": "https://maps.google.com/?q=6.1926012,1.1440171"
    },
    {
        "nom": "PHARMACIE AGBEGNIGAN",
        "photo": "pharmacie-agbegnigan.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 70 20 00 00",
        "contact_2": "",
        "email": "pharmacieagbegnigan@gmail.com",
        "adresse": "Près du PRET A MANGER, Tokoin Ramco - Gbadago, Av. de la Libération, Lomé, Togo",
        "latitude": "6.1470438",
        "longitude": "1.2192144",
        "map_link": "https://maps.google.com/?q=6.1470438,1.2192144"
    },
    {
        "nom": "Pharmacie 2000",
        "photo": "pharmacie-2000.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 91 64 73 38",
        "contact_2": "",
        "email": "pharmacie2000@yahoo.fr",
        "adresse": "Rue 258 HDN, Lomé, Togo",
        "latitude": "6.16397",
        "longitude": "1.268484",
        "map_link": "https://maps.google.com/?q=6.16397,1.268484"
    },
    {
        "nom": "Pharmacie Mathilda",
        "photo": "pharmacie-mathilda.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 22 51 15 34",
        "contact_2": "",
        "email": "pharmaciemathilda@outlook.com",
        "adresse": "Av. des Evalas, Lomé, Togo",
        "latitude": "6.1824439",
        "longitude": "1.2001174",
        "map_link": "https://maps.google.com/?q=6.1824439,1.2001174"
    },
    {
        "nom": "Forever Pharmacie",
        "photo": "forever-pharmacie.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 22 26 11 77",
        "contact_2": "",
        "email": "foreverpharmacie@gmail.com",
        "adresse": "Rue 125 TKW, Lomé, Togo",
        "latitude": "6.1596768",
        "longitude": "1.2264046",
        "map_link": "https://maps.google.com/?q=6.1596768,1.2264046"
    },
    {
        "nom": "GRAABEL PHARMA TOGO",
        "photo": "graabel-pharma.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "",
        "contact_2": "",
        "email": "graabelpharma@yahoo.fr",
        "adresse": "Lomé, Togo",
        "latitude": "6.1936616",
        "longitude": "1.1768582",
        "map_link": "https://maps.google.com/?q=6.1936616,1.1768582"
    },
    {
        "nom": "Pharmacie De L'Amitié",
        "photo": "pharmacie-amitie.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 22 25 47 74",
        "contact_2": "",
        "email": "pharmacieamitie@outlook.com",
        "adresse": "Lomé, Togo",
        "latitude": "6.1536525",
        "longitude": "1.2227872",
        "map_link": "https://maps.google.com/?q=6.1536525,1.2227872"
    },
    {
        "nom": "Pharmacie d'Aneho Woezon",
        "photo": "pharmacie-aneho-woezon.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 70 43 56 48",
        "contact_2": "",
        "email": "pharmacieaneho@gmail.com",
        "adresse": "Grand Popo, Lomé, Togo",
        "latitude": "6.1256983",
        "longitude": "1.2253621",
        "map_link": "https://maps.google.com/?q=6.1256983,1.2253621"
    },
    {
        "nom": "Pharmacie Akofa",
        "photo": "pharmacie-akofa.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 22 40 66 68",
        "contact_2": "",
        "email": "pharmacieakofa@yahoo.fr",
        "adresse": "Lomé, Togo",
        "latitude": "6.1431124",
        "longitude": "1.229963",
        "map_link": "https://maps.google.com/?q=6.1431124,1.229963"
    },
    {
        "nom": "Pharmacie Christ-Roi",
        "photo": "pharmacie-christ-roi.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 97 77 12 31",
        "contact_2": "",
        "email": "pharmaciechristroi@gmail.com",
        "adresse": "Lomé, Togo",
        "latitude": "6.164994",
        "longitude": "1.3019193",
        "map_link": "https://maps.google.com/?q=6.164994,1.3019193"
    },
    {
        "nom": "Pharmacie KEGUE",
        "photo": "pharmacie-kegue.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "",
        "contact_2": "",
        "email": "pharmaciekegue@outlook.com",
        "adresse": "665R+3JH, Lomé, Togo",
        "latitude": "6.2093484",
        "longitude": "1.2414393",
        "map_link": "https://maps.google.com/?q=6.2093484,1.2414393"
    },
    {
        "nom": "Pharmacie Fidelia",
        "photo": "pharmacie-fidelia.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 22 71 95 95",
        "contact_2": "",
        "email": "pharmaciefidelia@yahoo.fr",
        "adresse": "5788+GJP, Lomé, Togo",
        "latitude": "6.1663386",
        "longitude": "1.2665748",
        "map_link": "https://maps.google.com/?q=6.1663386,1.2665748"
    },
    {
        "nom": "Pharmacie La Grace",
        "photo": "pharmacie-la-grace.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 22 25 91 65",
        "contact_2": "",
        "email": "pharmacielagrace@gmail.com",
        "adresse": "N1, Lomé, Togo",
        "latitude": "6.2194451",
        "longitude": "1.2092257",
        "map_link": "https://maps.google.com/?q=6.2194451,1.2092257"
    },
    {
        "nom": "Pharmacie de Gbossimé",
        "photo": "pharmacie-gbossime.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 22 22 50 50",
        "contact_2": "",
        "email": "pharmaciegbossime@outlook.com",
        "adresse": "Gbossimé, 376 Bd de la Kara, Lomé, Togo",
        "latitude": "6.1593936",
        "longitude": "1.2055782",
        "map_link": "https://maps.google.com/?q=6.1593936,1.2055782"
    },
    {
        "nom": "Pharmacie À Dieu la Gloire",
        "photo": "pharmacie-dieu-gloire.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 93 26 36 00",
        "contact_2": "",
        "email": "pharmaciedieugloire@yahoo.fr",
        "adresse": "748X+XW2, Unnamed Road, Lomé, Togo",
        "latitude": "6.2673949",
        "longitude": "1.149772",
        "map_link": "https://maps.google.com/?q=6.2673949,1.149772"
    },
    {
        "nom": "Pharmacie Nabine",
        "photo": "pharmacie-nabine.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 96 32 97 79",
        "contact_2": "",
        "email": "pharmacienabine@gmail.com",
        "adresse": "Lomé, Togo",
        "latitude": "6.2182803",
        "longitude": "1.1826973",
        "map_link": "https://maps.google.com/?q=6.2182803,1.1826973"
    },
    {
        "nom": "Pharmacie Agoè-Nyivé",
        "photo": "pharmacie-agoe-nyive.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 22 25 83 38",
        "contact_2": "",
        "email": "pharmacieagoenyive@outlook.com",
        "adresse": "Eyadema, A côté de l'église catholique Marie Théotokos, Lomé, Togo",
        "latitude": "6.2251459",
        "longitude": "1.2105678",
        "map_link": "https://maps.google.com/?q=6.2251459,1.2105678"
    },
    {
        "nom": "PHARMACIE MAJESTE",
        "photo": "pharmacie-majeste.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 71 16 16 43",
        "contact_2": "",
        "email": "pharmaciemajeste@yahoo.fr",
        "adresse": "6C35+5P6 36BP76, Lomé, Togo",
        "latitude": "6.2029375",
        "longitude": "1.4093125",
        "map_link": "https://maps.google.com/?q=6.2029375,1.4093125"
    },
    {
        "nom": "Pharmacie Régina Pacis",
        "photo": "pharmacie-regina-pacis.jpg",
        "ville": "Adétikopé",
        "prefecture": "Agoènyivé",
        "pays": "Togo",
        "contact_1": "",
        "contact_2": "",
        "email": "pharmaciereginapacis@gmail.com",
        "adresse": "Adétikopé, Togo",
        "latitude": "6.3175488",
        "longitude": "1.2168493",
        "map_link": "https://maps.google.com/?q=6.3175488,1.2168493"
    },
    {
        "nom": "PHARMACIE BAKOE",
        "photo": "pharmacie-bakoe.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 90 96 16 08",
        "contact_2": "",
        "email": "pharmaciebakoe@outlook.com",
        "adresse": "S/c 13BP36, Lomé, Togo",
        "latitude": "6.2853963",
        "longitude": "1.1417119",
        "map_link": "https://maps.google.com/?q=6.2853963,1.1417119"
    },
    {
        "nom": "Pharmacie Assurance",
        "photo": "pharmacie-assurance.jpg",
        "ville": "Adétikopé",
        "prefecture": "Agoènyivé",
        "pays": "Togo",
        "contact_1": "",
        "contact_2": "",
        "email": "pharmacieassurance@yahoo.fr",
        "adresse": "86C9+92F, Adétikopé, Togo",
        "latitude": "6.3209304",
        "longitude": "1.21755",
        "map_link": "https://maps.google.com/?q=6.3209304,1.21755"
    },
    {
        "nom": "Pharmacie Togblé-Kopé",
        "photo": "pharmacie-togble-kope.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 97 98 09 59",
        "contact_2": "",
        "email": "pharmacietogblekope@gmail.com",
        "adresse": "Lomé, Togo",
        "latitude": "6.2703936",
        "longitude": "1.2103609",
        "map_link": "https://maps.google.com/?q=6.2703936,1.2103609"
    },
    {
        "nom": "Pharmacie Amen",
        "photo": "pharmacie-amen.jpg",
        "ville": "Adétikopé",
        "prefecture": "Agoènyivé",
        "pays": "Togo",
        "contact_1": "+228 90 88 55 88",
        "contact_2": "",
        "email": "pharmacieamen@outlook.com",
        "adresse": "86CF+395, Adétikopé, Togo",
        "latitude": "6.3201345",
        "longitude": "1.2234853",
        "map_link": "https://maps.google.com/?q=6.3201345,1.2234853"
    },
    {
        "nom": "Pharmacie Conseil",
        "photo": "pharmacie-conseil.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 93 10 92 92",
        "contact_2": "",
        "email": "pharmacieconseil@yahoo.fr",
        "adresse": "Route de Segbé, Lomé, Togo",
        "latitude": "6.4364162",
        "longitude": "1.1748619",
        "map_link": "https://maps.google.com/?q=6.4364162,1.1748619"
    },
    {
        "nom": "Pharmacie M'BA",
        "photo": "pharmacie-mba.jpg",
        "ville": "Lomé",
        "prefecture": "Golfe",
        "pays": "Togo",
        "contact_1": "+228 70 27 81 81",
        "contact_2": "+228 99 76 81 81",
        "email": "pharmaciemba@gmail.com",
        "adresse": "13 BP 341 Lomé. Route de Kovié, 500 mètres après le marché de LEGBASSITO",
        "latitude": "6.2716545",
        "longitude": "1.1486506",
        "map_link": "https://maps.google.com/?q=6.2716545,1.1486506"
    },
    {
        "nom": "Pharmacie Believe",
        "photo": "pharmacie-believe.jpg",
        "ville": "Tsévié",
        "prefecture": "Zio",
        "pays": "Togo",
        "contact_1": "+228 96 80 10 23",
        "contact_2": "",
        "email": "pharmaciebelieve@outlook.com",
        "adresse": "C6C6+2JR, Tsévié, Togo",
        "latitude": "6.4200943",
        "longitude": "1.2114737",
        "map_link": "https://maps.google.com/?q=6.4200943,1.2114737"
    },
    {
        "nom": "Pharmacie koboyo",
        "photo": "pharmacie-koboyo.jpg",
        "ville": "Dalavé",
        "prefecture": "Zio",
        "pays": "Togo",
        "contact_1": "+228 93 70 48 12",
        "contact_2": "",
        "email": "pharmaciekoboyo@yahoo.fr",
        "adresse": "03 bp 30360, Dalavé, Togo",
        "latitude": "6.3514611",
        "longitude": "1.2117051",
        "map_link": "https://maps.google.com/?q=6.3514611,1.2117051"
    },
    {
        "nom": "PRA TSÉVIÉ",
        "photo": "pra-tsevie.jpg",
        "ville": "Tsévié",
        "prefecture": "Zio",
        "pays": "Togo",
        "contact_1": "+228 93 66 70 38",
        "contact_2": "",
        "email": "pratsévie@gmail.com",
        "adresse": "8349, Tsévié, Togo",
        "latitude": "6.4323273",
        "longitude": "1.2219817",
        "map_link": "https://maps.google.com/?q=6.4323273,1.2219817"
    },
    {
        "nom": "Pharmacie de la Gare",
        "photo": "pharmacie-gare-kpalime.jpg",
        "ville": "Kpalimé",
        "prefecture": "Kloto",
        "pays": "Togo",
        "contact_1": "+228 24 41 01 20",
        "contact_2": "",
        "email": "pharmaciegarekpalime@gmail.com",
        "adresse": "Kpalimé, Togo",
        "latitude": "6.9069537",
        "longitude": "0.6338943",
        "map_link": "https://maps.google.com/?q=6.9069537,0.6338943"
    },
    {
        "nom": "Pharmacie LA PERSEVERANCE",
        "photo": "pharmacie-perseverance.jpg",
        "ville": "Kpalimé",
        "prefecture": "Kloto",
        "pays": "Togo",
        "contact_1": "+228 90 14 48 57",
        "contact_2": "",
        "email": "pharmacieperseverance@outlook.com",
        "adresse": "Atakpamekondji en face du super marche, Kpalimé, Togo",
        "latitude": "6.9156404",
        "longitude": "0.6337423",
        "map_link": "https://maps.google.com/?q=6.9156404,0.6337423"
    },
    {
        "nom": "Pharmacie Kékéli",
        "photo": "pharmacie-kekeli.jpg",
        "ville": "Kpalimé",
        "prefecture": "Kloto",
        "pays": "Togo",
        "contact_1": "+228 99 99 22 49",
        "contact_2": "",
        "email": "pharmaciekekeli@gmail.com",
        "adresse": "Route Nationale N5, Kpalimé, Togo",
        "latitude": "6.9189588",
        "longitude": "0.6341771",
        "map_link": "https://maps.google.com/?q=6.9189588,0.6341771"
    },
    {
        "nom": "Dépôt de Pharmacie le MÉDIATEUR",
        "photo": "depot-mediateur.jpg",
        "ville": "Adéta",
        "prefecture": "Kloto",
        "pays": "Togo",
        "contact_1": "+228 97 42 16 18",
        "contact_2": "",
        "email": "depotmediateur@yahoo.fr",
        "adresse": "Rond Point d, Adéta, Togo",
        "latitude": "7.1272334",
        "longitude": "0.7312264",
        "map_link": "https://maps.google.com/?q=7.1272334,0.7312264"
    },
    {
        "nom": "Pharmacie La Vie",
        "photo": "pharmacie-la-vie.jpg",
        "ville": "Notsé",
        "prefecture": "Haho",
        "pays": "Togo",
        "contact_1": "+228 24 42 01 27",
        "contact_2": "",
        "email": "pharmacielavie@outlook.com",
        "adresse": "Unnamed Road, Notsé, Togo",
        "latitude": "6.950667",
        "longitude": "1.1727279",
        "map_link": "https://maps.google.com/?q=6.950667,1.1727279"
    },
    {
        "nom": "DYNACE GLOBAL TOGO",
        "photo": "dynace-global.jpg",
        "ville": "Atakpamé",
        "prefecture": "Ogou",
        "pays": "Togo",
        "contact_1": "+228 90 32 15 55",
        "contact_2": "",
        "email": "dynaceglobal@gmail.com",
        "adresse": "Agbonou, BP: 09, Atakpamé, Togo",
        "latitude": "7.5216738",
        "longitude": "1.1479709",
        "map_link": "https://maps.google.com/?q=7.5216738,1.1479709"
    },
    {
        "nom": "Nkoko ÉWÉ",
        "photo": "nkoko-ewe.jpg",
        "ville": "Atakpamé",
        "prefecture": "Ogou",
        "pays": "Togo",
        "contact_1": "",
        "contact_2": "",
        "email": "nkokoewe@yahoo.fr",
        "adresse": "Atakpamé, Togo",
        "latitude": "7.5256427",
        "longitude": "1.1492409",
        "map_link": "https://maps.google.com/?q=7.5256427,1.1492409"
    },
    {
        "nom": "PRODUITS VESTIGE Atakpamé",
        "photo": "vestige-atakpame.jpg",
        "ville": "Atakpamé",
        "prefecture": "Ogou",
        "pays": "Togo",
        "contact_1": "+228 99 42 08 37",
        "contact_2": "",
        "email": "vestigeatakpame@outlook.com",
        "adresse": "BP: 09 Agbonou, Atakpamé, Togo",
        "latitude": "7.5218772",
        "longitude": "1.148022",
        "map_link": "https://maps.google.com/?q=7.5218772,1.148022"
    },
    {
        "nom": "Pharmacie Peniel",
        "photo": "pharmacie-peniel.jpg",
        "ville": "Atakpamé",
        "prefecture": "Ogou",
        "pays": "Togo",
        "contact_1": "+228 70 39 72 02",
        "contact_2": "",
        "email": "pharmaciepeniel@gmail.com",
        "adresse": "Rue du Marché, Atakpamé, Togo",
        "latitude": "7.5318591",
        "longitude": "1.1221556",
        "map_link": "https://maps.google.com/?q=7.5318591,1.1221556"
    },
    {
        "nom": "Pharmacie Zénith",
        "photo": "pharmacie-zenith.jpg",
        "ville": "Anié",
        "prefecture": "Anié",
        "pays": "Togo",
        "contact_1": "+228 93 44 68 68",
        "contact_2": "",
        "email": "pharmaciezenith@yahoo.fr",
        "adresse": "6000, Anié, Togo",
        "latitude": "7.7563008",
        "longitude": "1.1978009",
        "map_link": "https://maps.google.com/?q=7.7563008,1.1978009"
    },
    {
        "nom": "VET-PLUS Pharmacie et clinique Vétérinaires",
        "photo": "vet-plus.jpg",
        "ville": "Anié",
        "prefecture": "Anié",
        "pays": "Togo",
        "contact_1": "+228 70 35 40 05",
        "contact_2": "",
        "email": "vetplusanie@outlook.com",
        "adresse": "N1, Anié, Togo",
        "latitude": "7.7576638",
        "longitude": "1.1937159",
        "map_link": "https://maps.google.com/?q=7.7576638,1.1937159"
    },
    {
        "nom": "Depôt de pharmacie Hosanna",
        "photo": "depot-hosanna.jpg",
        "ville": "Sotouboua",
        "prefecture": "Sotouboua",
        "pays": "Togo",
        "contact_1": "",
        "contact_2": "",
        "email": "depothosanna@gmail.com",
        "adresse": "Unnamed Road, Sotouboua, Togo",
        "latitude": "8.5579306",
        "longitude": "0.9851516",
        "map_link": "https://maps.google.com/?q=8.5579306,0.9851516"
    },
    {
        "nom": "Pharmacie Nouvelle",
        "photo": "pharmacie-nouvelle.jpg",
        "ville": "Sokodé",
        "prefecture": "Tchaoudjo",
        "pays": "Togo",
        "contact_1": "+228 90 72 36 39",
        "contact_2": "",
        "email": "pharmacienouvelle@yahoo.fr",
        "adresse": "Route de Bassar en face de GIPATO, Sokode, Togo",
        "latitude": "8.9870902",
        "longitude": "1.1361711",
        "map_link": "https://maps.google.com/?q=8.9870902,1.1361711"
    },
    {
        "nom": "Pharmacie Renaissance",
        "photo": "pharmacie-renaissance.jpg",
        "ville": "Lama-Kara",
        "prefecture": "Kozah",
        "pays": "Togo",
        "contact_1": "+228 26 60 09 39",
        "contact_2": "",
        "email": "pharmacierenaissance@outlook.com",
        "adresse": "N1, Lama-Kara, Togo",
        "latitude": "9.5390286",
        "longitude": "1.1965257",
        "map_link": "https://maps.google.com/?q=9.5390286,1.1965257"
    },
    {
        "nom": "Pharmacie de L'espoir",
        "photo": "pharmacie-espoir-kara.jpg",
        "ville": "Kara",
        "prefecture": "Kozah",
        "pays": "Togo",
        "contact_1": "+228 22 26 14 15",
        "contact_2": "",
        "email": "pharmacieespoirkara@gmail.com",
        "adresse": "443, Togo",
        "latitude": "9.5470657",
        "longitude": "1.1893136",
        "map_link": "https://maps.google.com/?q=9.5470657,1.1893136"
    },
    {
        "nom": "Pharmacie de la Kozah",
        "photo": "pharmacie-kozah.jpg",
        "ville": "Kara",
        "prefecture": "Kozah",
        "pays": "Togo",
        "contact_1": "",
        "contact_2": "",
        "email": "pharmaciekozah@yahoo.fr",
        "adresse": "G5XQ+VR9, Kara, Togo",
        "latitude": "9.549366",
        "longitude": "1.189666",
        "map_link": "https://maps.google.com/?q=9.549366,1.189666"
    },
    {
        "nom": "Pharmacie Kara centre",
        "photo": "pharmacie-kara-centre.jpg",
        "ville": "Kara",
        "prefecture": "Kozah",
        "pays": "Togo",
        "contact_1": "",
        "contact_2": "",
        "email": "pharmaciekaracentre@outlook.com",
        "adresse": "N1, Kara, Togo",
        "latitude": "9.5516795",
        "longitude": "1.1969161",
        "map_link": "https://maps.google.com/?q=9.5516795,1.1969161"
    },
    {
        "nom": "Pharmacie LAFIA Kara",
        "photo": "pharmacie-lafia.jpg",
        "ville": "Kara",
        "prefecture": "Kozah",
        "pays": "Togo",
        "contact_1": "+228 90 69 26 65",
        "contact_2": "",
        "email": "pharmacielafia@gmail.com",
        "adresse": "BP 500 COFAC KARA, Togo",
        "latitude": "9.5475227",
        "longitude": "1.1945205",
        "map_link": "https://maps.google.com/?q=9.5475227,1.1945205"
    },
    {
        "nom": "PHARMACIE DU NOUVEAU MARCHE KARA",
        "photo": "pharmacie-nouveau-marche.jpg",
        "ville": "Kara",
        "prefecture": "Kozah",
        "pays": "Togo",
        "contact_1": "+228 93 27 77 77",
        "contact_2": "",
        "email": "pharmacienouveaumarche@yahoo.fr",
        "adresse": "BP 32, Kara, Togo",
        "latitude": "9.5608618",
        "longitude": "1.1918158",
        "map_link": "https://maps.google.com/?q=9.5608618,1.1918158"
    },
    {
        "nom": "Pharmacie Janil-Togo",
        "photo": "pharmacie-janil.jpg",
        "ville": "Guérin-Kouka",
        "prefecture": "Kozah",
        "pays": "Togo",
        "contact_1": "",
        "contact_2": "",
        "email": "pharmaciejanil@outlook.com",
        "adresse": "Guérin-Kouka, Togo",
        "latitude": "9.6909536",
        "longitude": "0.6080622",
        "map_link": "https://maps.google.com/?q=9.6909536,0.6080622"
    },
    {
        "nom": "PHARMACIE FOREVER",
        "photo": "pharmacie-forever-tchamba.jpg",
        "ville": "Tchamba",
        "prefecture": "Tchamba",
        "pays": "Togo",
        "contact_1": "",
        "contact_2": "",
        "email": "pharmacieforever@yahoo.fr",
        "adresse": "Tchamba, Togo",
        "latitude": "9.023886",
        "longitude": "1.4288068",
        "map_link": "https://maps.google.com/?q=9.023886,1.4288068"
    },
    {
        "nom": "Pharmacie SAVANA",
        "photo": "pharmacie-savana.jpg",
        "ville": "Dapaong",
        "prefecture": "Tône",
        "pays": "Togo",
        "contact_1": "+228 27 70 12 58",
        "contact_2": "",
        "email": "pharmaciesavana@gmail.com",
        "adresse": "87, Dapaong, Togo",
        "latitude": "10.8617542",
        "longitude": "0.2049895",
        "map_link": "https://maps.google.com/?q=10.8617542,0.2049895"
    },
    {
        "nom": "Pharmacie Le Sauveur",
        "photo": "pharmacie-sauveur.jpg",
        "ville": "Dapaong",
        "prefecture": "Tône",
        "pays": "Togo",
        "contact_1": "+228 27 70 81 28",
        "contact_2": "",
        "email": "pharmaciesauveur@outlook.com",
        "adresse": "Dapaong, Togo",
        "latitude": "10.8688249",
        "longitude": "0.2022855",
        "map_link": "https://maps.google.com/?q=10.8688249,0.2022855"
    },
    {
        "nom": "VETO NEGOCES",
        "photo": "veto-negoces.jpg",
        "ville": "Cinkassé",
        "prefecture": "Tône",
        "pays": "Togo",
        "contact_1": "+228 90 04 64 38",
        "contact_2": "",
        "email": "vetonegoces@yahoo.fr",
        "adresse": "75, Cinkassé, Togo",
        "latitude": "11.1059574",
        "longitude": "0.014598",
        "map_link": "https://maps.google.com/?q=11.1059574,0.014598"
    },
    {
        "nom": "UNI-COS",
        "photo": "uni-cos.jpg",
        "ville": "Kara",
        "prefecture": "Kozah",
        "pays": "Togo",
        "contact_1": "+228 92 52 52 14",
        "contact_2": "",
        "email": "unicoskara@gmail.com",
        "adresse": "Kara, Togo",
        "latitude": "9.547972",
        "longitude": "1.1895671",
        "map_link": "https://maps.google.com/?q=9.547972,1.1895671"
    },
    {
        nom: "Pharmacie Camp Guezo",
        photo: "pharmacie-camp-guezo.jpg",
        ville: "Cotonou",
        prefecture: "Littoral",
        pays: "Bénin",
        contact_1: "+229 01 21 31 35 55",
        contact_2: "",
        email: "info@pharmaciecampguezo.net",
        adresse: "Unnamed Road, Cotonou, Bénin",
        latitude: "6.3561453",
        longitude: "2.4182102",
        map_link: "https://maps.google.com/?q=6.3561453,2.4182102"
    },
    {
        nom: "Pharmacie Cristal Santé",
        photo: "pharmacie-cristal-sante.jpg",
        ville: "Cotonou",
        prefecture: "Littoral",
        pays: "Bénin",
        contact_1: "+229 01 94 51 59 29",
        contact_2: "",
        email: "pharmaciecristalsante@outlook.com",
        adresse: "99H3+889, Unnamed Road, Cotonou, Bénin",
        latitude: "6.3782813",
        longitude: "2.3533605",
        map_link: "https://maps.google.com/?q=6.3782813,2.3533605"
    },
    {
        nom: "Pharmacie Agblangandan",
        photo: "pharmacie-agblangandan.jpg",
        ville: "Agblangandan",
        prefecture: "Ouémé",
        pays: "Bénin",
        contact_1: "",
        contact_2: "",
        email: "pharmacieagblangandan@yahoo.fr",
        adresse: "9FGP+4J2, Agblangandan, Bénin",
        latitude: "6.3752735",
        longitude: "2.4865157",
        map_link: "https://maps.google.com/?q=6.3752735,2.4865157"
    },
    {
        nom: "Pharmacie Godomey Fignonhou",
        photo: "pharmacie-godomey-fignonhou.jpg",
        ville: "Cotonou",
        prefecture: "Littoral",
        pays: "Bénin",
        contact_1: "+229 01 95 14 48 42",
        contact_2: "",
        email: "pharmaciegodomey@gmail.com",
        adresse: "Unnamed Road, Cotonou, Bénin",
        latitude: "6.3741922",
        longitude: "2.3406945",
        map_link: "https://maps.google.com/?q=6.3741922,2.3406945"
    },
    {
        nom: "Pharmacie Adjibadé",
        photo: "pharmacie-adjibade.jpg",
        ville: "Porto-Novo",
        prefecture: "Ouémé",
        pays: "Bénin",
        contact_1: "+229 01 57 28 08 96",
        contact_2: "",
        email: "pharmacieadjibade@outlook.com",
        adresse: "FJQF+CVW, Porto-Novo, Bénin",
        latitude: "6.4911696",
        longitude: "2.6254872",
        map_link: "https://maps.google.com/?q=6.4911696,2.6254872"
    },
    {
        nom: "Pharmacie Tanto le joker",
        photo: "pharmacie-tanto-joker.jpg",
        ville: "Cotonou",
        prefecture: "Littoral",
        pays: "Bénin",
        contact_1: "+229 01 97 05 66 06",
        contact_2: "",
        email: "pharmacietanto@gmail.com",
        adresse: "Cotonou, Bénin",
        latitude: "6.3713125",
        longitude: "2.4721875",
        map_link: "https://maps.google.com/?q=6.3713125,2.4721875"
    },
    {
        nom: "Pharmacie Bien-être",
        photo: "pharmacie-bien-etre.jpg",
        ville: "Cotonou",
        prefecture: "Littoral",
        pays: "Bénin",
        contact_1: "+229 01 60 50 70 50",
        contact_2: "",
        email: "pharmaciebienetre@yahoo.fr",
        adresse: "9FJC+JWC, Rue 1315, Cotonou, Bénin",
        latitude: "6.3816872",
        longitude: "2.4722781",
        map_link: "https://maps.google.com/?q=6.3816872,2.4722781"
    },
    {
        nom: "Pharmacie MAHUENA",
        photo: "pharmacie-mahuena.jpg",
        ville: "Cotonou",
        prefecture: "Littoral",
        pays: "Bénin",
        contact_1: "+229 01 90 15 56 96",
        contact_2: "",
        email: "pharmaciemahuena@gmail.com",
        adresse: "01 Bp 960 Carré 145 Scoa, Cotonou, Bénin",
        latitude: "6.360405",
        longitude: "2.4307522",
        map_link: "https://maps.google.com/?q=6.360405,2.4307522"
    },
    {
        nom: "Pharmacie Dowa Gbago Tabita",
        photo: "pharmacie-dowa-gbago.jpg",
        ville: "Cotonou",
        prefecture: "Littoral",
        pays: "Bénin",
        contact_1: "+229 01 68 63 65 20",
        contact_2: "",
        email: "pharmaciedowa@outlook.com",
        adresse: "06, Cotonou, Bénin",
        latitude: "6.5099869",
        longitude: "2.5963394",
        map_link: "https://maps.google.com/?q=6.5099869,2.5963394"
    },
    {
        nom: "Pharmacie Atinkanme",
        photo: "pharmacie-atinkanme.jpg",
        ville: "Cotonou",
        prefecture: "Littoral",
        pays: "Bénin",
        contact_1: "+229 01 60 01 97 72",
        contact_2: "",
        email: "pharmacieatinkanme@yahoo.fr",
        adresse: "Boulevard Steinmetz, Cotonou, Bénin",
        latitude: "6.3616264",
        longitude: "2.4343739",
        map_link: "https://maps.google.com/?q=6.3616264,2.4343739"
    },
    {
        nom: "PHARMACIE CATCHI",
        photo: "pharmacie-catchi.jpg",
        ville: "Porto-Novo",
        prefecture: "Ouémé",
        pays: "Bénin",
        contact_1: "+229 01 98 53 34 34",
        contact_2: "",
        email: "Pharmaciecatchi@gmail.com",
        adresse: "bp 67, Porto-Novo, Bénin",
        latitude: "6.4845021",
        longitude: "2.6208772",
        map_link: "https://maps.google.com/?q=6.4845021,2.6208772"
    },
    {
        nom: "Nouvelle Pharmacie Dona deï",
        photo: "pharmacie-dona-dei.jpg",
        ville: "Agblangandan",
        prefecture: "Ouémé",
        pays: "Bénin",
        contact_1: "+229 01 52 58 76 76",
        contact_2: "",
        email: "pharmaciedonadei@gmail.com",
        adresse: "BP 3384, Agblangandan, Bénin",
        latitude: "6.3696694",
        longitude: "2.5212497",
        map_link: "https://maps.google.com/?q=6.3696694,2.5212497"
    },
    {
        nom: "Pharmacie Koutongbé",
        photo: "pharmacie-koutongbe.jpg",
        ville: "Porto-Novo",
        prefecture: "Ouémé",
        pays: "Bénin",
        contact_1: "",
        contact_2: "",
        email: "pharmaciekoutongbe@outlook.com",
        adresse: "FJVQ+55F, Porto-Novo, Bénin",
        latitude: "6.4929253",
        longitude: "2.6379207",
        map_link: "https://maps.google.com/?q=6.4929253,2.6379207"
    },
    {
        nom: "Pharmacie Boulevard Djassin",
        photo: "pharmacie-boulevard-djassin.jpg",
        ville: "Porto-Novo",
        prefecture: "Ouémé",
        pays: "Bénin",
        contact_1: "+229 01 95 60 43 43",
        contact_2: "",
        email: "pharmaciedjassin@yahoo.fr",
        adresse: "FJH4+482, Porto-Novo, Bénin",
        latitude: "6.4777614",
        longitude: "2.60575",
        map_link: "https://maps.google.com/?q=6.4777614,2.60575"
    },
    {
        nom: "Pharmacie Malanhoui",
        photo: "pharmacie-malanhoui.jpg",
        ville: "Adjarra",
        prefecture: "Ouémé",
        pays: "Bénin",
        contact_1: "+229 01 95 39 12 53",
        contact_2: "",
        email: "pharmaciemalanhoui@gmail.com",
        adresse: "FMQ8+X4H, Adjarra, Bénin",
        latitude: "6.489943",
        longitude: "2.665357",
        map_link: "https://maps.google.com/?q=6.489943,2.665357"
    },
    {
        nom: "Pharmacie Espace Santé",
        photo: "pharmacie-espace-sante.jpg",
        ville: "Cotonou",
        prefecture: "Littoral",
        pays: "Bénin",
        contact_1: "+229 01 67 30 95 51",
        contact_2: "",
        email: "pharmacieespacesante@outlook.com",
        adresse: "Cotonou, Bénin",
        latitude: "6.3833853",
        longitude: "2.3349784",
        map_link: "https://maps.google.com/?q=6.3833853,2.3349784"
    },
    {
        nom: "Pharmacie Djèrègbé",
        photo: "pharmacie-djeregbé.jpg",
        ville: "Djéregbé",
        prefecture: "Ouémé",
        pays: "Bénin",
        contact_1: "",
        contact_2: "",
        email: "pharmaciedjeregbé@yahoo.fr",
        adresse: "CJCH+89V, Djéregbé, Bénin",
        latitude: "6.4208655",
        longitude: "2.6284215",
        map_link: "https://maps.google.com/?q=6.4208655,2.6284215"
    },
    {
        nom: "Pharmacie Kpedetin",
        photo: "pharmacie-kpedetin.jpg",
        ville: "Akpro-Missérété",
        prefecture: "Ouémé",
        pays: "Bénin",
        contact_1: "",
        contact_2: "",
        email: "pharmaciekpedetin@gmail.com",
        adresse: "HH8M+GMW, Akpro-Missérété, Bénin",
        latitude: "6.5663743",
        longitude: "2.5842062",
        map_link: "https://maps.google.com/?q=6.5663743,2.5842062"
    },
    {
        nom: "PHARMACIE ADOUNI",
        photo: "pharmacie-adouni.jpg",
        ville: "Akpro-Misserete",
        prefecture: "Ouémé",
        pays: "Bénin",
        contact_1: "",
        contact_2: "",
        email: "pharmacieadouni@outlook.com",
        adresse: "HH7Q+FHP, RNIE1, Akpro-Misserete, Bénin",
        latitude: "6.5637088",
        longitude: "2.5889674",
        map_link: "https://maps.google.com/?q=6.5637088,2.5889674"
    },
    {
        nom: "PHARMACIE OLABISSI -IKPNINLE",
        photo: "pharmacie-olabissi-ikpninle.jpg",
        ville: "Banigbé",
        prefecture: "Ouémé",
        pays: "Bénin",
        contact_1: "",
        contact_2: "",
        email: "pharmacieolabissi@yahoo.fr",
        adresse: "VJQ9+QG, Banigbé, Bénin",
        latitude: "6.8894313",
        longitude: "2.6188292",
        map_link: "https://maps.google.com/?q=6.8894313,2.6188292"
    },
    {
        nom: "Pharmacie Zinvié",
        photo: "pharmacie-zinvie.jpg",
        ville: "Zinvié",
        prefecture: "Atlantique",
        pays: "Bénin",
        contact_1: "",
        contact_2: "",
        email: "pharmaciezinvie@gmail.com",
        adresse: "J955+RCQ, Zinvié, Bénin",
        latitude: "6.6095876",
        longitude: "2.3585942",
        map_link: "https://maps.google.com/?q=6.6095876,2.3585942"
    },
    {
        nom: "PHARMACIE NOUVEL ESPOIR (AVRANKOU)",
        photo: "pharmacie-nouvel-espoir.jpg",
        ville: "AVRANKOU",
        prefecture: "Ouémé",
        pays: "Bénin",
        contact_1: "+229 01 96 94 41 97",
        contact_2: "",
        email: "pharmacienouvelespoir@outlook.com",
        adresse: "BP 80, AVRANKOU, Bénin",
        latitude: "6.5548047",
        longitude: "2.6582846",
        map_link: "https://maps.google.com/?q=6.5548047,2.6582846"
    },
    {
        nom: "PHARMACIE FIFAME",
        photo: "pharmacie-fifame.jpg",
        ville: "RNIE2",
        prefecture: "Atlantique",
        pays: "Bénin",
        contact_1: "+229 01 69 03 45 45",
        contact_2: "",
        email: "pharmaciefifame@yahoo.fr",
        adresse: "RNIE2, Bénin",
        latitude: "6.5279848",
        longitude: "2.3526453",
        map_link: "https://maps.google.com/?q=6.5279848,2.3526453"
    },
    {
        nom: "PHARMACIE LES ANGES",
        photo: "pharmacie-les-anges.jpg",
        ville: "Dangbo",
        prefecture: "Ouémé",
        pays: "Bénin",
        contact_1: "",
        contact_2: "",
        email: "pharmacielesanges@gmail.com",
        adresse: "HHM3+3QH, RN4, Dangbo, Bénin",
        latitude: "6.5826935",
        longitude: "2.5544844",
        map_link: "https://maps.google.com/?q=6.5826935,2.5544844"
    },
    {
        nom: "Pharmacie Olabissi D'ikpinlè",
        photo: "pharmacie-olabissi-ikpinle.jpg",
        ville: "Sakété",
        prefecture: "Plateau",
        pays: "Bénin",
        contact_1: "",
        contact_2: "",
        email: "pharmacieolabissiikpinle@outlook.com",
        adresse: "VJQ9+VPM, RN3, Sakété, Bénin",
        latitude: "6.889715",
        longitude: "2.6192955",
        map_link: "https://maps.google.com/?q=6.889715,2.6192955"
    },
    {
        nom: "Pharmacie Tanzoun",
        photo: "pharmacie-tanzoun.jpg",
        ville: "Porto-Novo",
        prefecture: "Ouémé",
        pays: "Bénin",
        contact_1: "",
        contact_2: "",
        email: "pharmacietanzoun@yahoo.fr",
        adresse: "GJGG+F36, Porto-Novo, Bénin",
        latitude: "6.5261527",
        longitude: "2.6251464",
        map_link: "https://maps.google.com/?q=6.5261527,2.6251464"
    },
    {
        nom: "Pharmacie du Grand Marché",
        photo: "pharmacie-grand-marche.jpg",
        ville: "Porto-Novo",
        prefecture: "Ouémé",
        pays: "Bénin",
        contact_1: "",
        contact_2: "",
        email: "pharmaciegrandmarche@gmail.com",
        adresse: "FJCG+JGW, Porto-Novo, Bénin",
        latitude: "6.4716089",
        longitude: "2.6263423",
        map_link: "https://maps.google.com/?q=6.4716089,2.6263423"
    },
    {
        nom: "PHARMACIE St Raymond du Marché Agata",
        photo: "pharmacie-st-raymond.jpg",
        ville: "Porto-Novo",
        prefecture: "Ouémé",
        pays: "Bénin",
        contact_1: "",
        contact_2: "",
        email: "pharmaciestraymond@outlook.com",
        adresse: "2ème Arrondissement, Porto-Novo, Bénin",
        latitude: "6.5012609",
        longitude: "2.6481491",
        map_link: "https://maps.google.com/?q=6.5012609,2.6481491"
    },
    {
        nom: "Pharmacie Cité de Paix Houegbo",
        photo: "pharmacie-cite-paix.jpg",
        ville: "Houegbo",
        prefecture: "Atlantique",
        pays: "Bénin",
        contact_1: "",
        contact_2: "",
        email: "pharmacieciteepaix@yahoo.fr",
        adresse: "R56F+GX7, RNIE2, Bénin",
        latitude: "6.8112811",
        longitude: "2.1749119",
        map_link: "https://maps.google.com/?q=6.8112811,2.1749119"
    },
    {
        nom: "PHARMACIE ENORYVES",
        photo: "pharmacie-enoryves.jpg",
        ville: "Pobé",
        prefecture: "Plateau",
        pays: "Bénin",
        contact_1: "+229 01 62 42 72 72",
        contact_2: "",
        email: "pharmacieenoryves@gmail.com",
        adresse: "Pobé, Bénin",
        latitude: "6.9832937",
        longitude: "2.6635667",
        map_link: "https://maps.google.com/?q=6.9832937,2.6635667"
    },
    {
        nom: "Pharmacie Sèhouè",
        photo: "pharmacie-sehoue.jpg",
        ville: "Sérouhé",
        prefecture: "Atlantique",
        pays: "Bénin",
        contact_1: "",
        contact_2: "",
        email: "pharmaciesehoue@outlook.com",
        adresse: "W797+MX, Sérouhé, Bénin",
        latitude: "6.9191969",
        longitude: "2.2648658",
        map_link: "https://maps.google.com/?q=6.9191969,2.2648658"
    },
    {
        nom: "Pharmacie Nouvelle EVE",
        photo: "pharmacie-nouvelle-eve.jpg",
        ville: "Adjian",
        prefecture: "Atlantique",
        pays: "Bénin",
        contact_1: "",
        contact_2: "",
        email: "pharmacienouvelleeve@yahoo.fr",
        adresse: "P7CP+5W, Adjian, Bénin",
        latitude: "6.721071",
        longitude: "2.288332",
        map_link: "https://maps.google.com/?q=6.721071,2.288332"
    },
    {
        nom: "Pharmacie Centrale de Houegbo",
        photo: "pharmacie-centrale-houegbo.jpg",
        ville: "Houegbo",
        prefecture: "Atlantique",
        pays: "Bénin",
        contact_1: "",
        contact_2: "",
        email: "pharmaciecentralehouegbo@gmail.com",
        adresse: "R52C+7RR, Commune de toffo, Houegbo, Bénin",
        latitude: "6.8007389",
        longitude: "2.172022",
        map_link: "https://maps.google.com/?q=6.8007389,2.172022"
    },
    {
        nom: "Pharmacie Zogbodomey",
        photo: "pharmacie-zogbodomey.jpg",
        ville: "Zogbodomey",
        prefecture: "Zou",
        pays: "Bénin",
        contact_1: "",
        contact_2: "",
        email: "pharmaciezogbodomey@outlook.com",
        adresse: "34F5+CRG, RNIE2, Bénin",
        latitude: "7.0735578",
        longitude: "2.1095862",
        map_link: "https://maps.google.com/?q=7.0735578,2.1095862"
    },
    {
        nom: "PHARMACIE ATTOGON",
        photo: "pharmacie-attogon.jpg",
        ville: "Attogon",
        prefecture: "Atlantique",
        pays: "Bénin",
        contact_1: "",
        contact_2: "",
        email: "pharmacieattogon@yahoo.fr",
        adresse: "P5J7+6CW, Attogon, Bénin",
        latitude: "6.7306097",
        longitude: "2.163585",
        map_link: "https://maps.google.com/?q=6.7306097,2.163585"
    },
    {
        nom: "Pharmacie Saint Henri",
        photo: "pharmacie-saint-henri.jpg",
        ville: "Bohicon",
        prefecture: "Zou",
        pays: "Bénin",
        contact_1: "+229 01 94 01 22 27",
        contact_2: "",
        email: "pharmaciesainthenri@gmail.com",
        adresse: "RNIE2, Bohicon, Bénin",
        latitude: "7.1813072",
        longitude: "2.067334",
        map_link: "https://maps.google.com/?q=7.1813072,2.067334"
    },
    {
        nom: "Pharmacie HOUEFA",
        photo: "pharmacie-houefa.jpg",
        ville: "Bohicon",
        prefecture: "Zou",
        pays: "Bénin",
        contact_1: "+229 01 95 17 00 60",
        contact_2: "",
        email: "pharmaciehouefa@outlook.com",
        adresse: "53CR+H3F, Bohicon, Bénin",
        latitude: "7.1714293",
        longitude: "2.090158",
        map_link: "https://maps.google.com/?q=7.1714293,2.090158"
    },
    {
        nom: "Pharmacie De l'Etoile De Kpokon",
        photo: "pharmacie-etoile-kpokon.jpg",
        ville: "Bohicon",
        prefecture: "Zou",
        pays: "Bénin",
        contact_1: "",
        contact_2: "",
        email: "pharmacieetoilekpokon@yahoo.fr",
        adresse: "53J7+5FX, Bohicon, Bénin",
        latitude: "7.18048",
        longitude: "2.06373",
        map_link: "https://maps.google.com/?q=7.18048,2.06373"
    },
    {
        nom: "Pharmacie sainte face",
        photo: "pharmacie-sainte-face.jpg",
        ville: "Bohicon",
        prefecture: "Zou",
        pays: "Bénin",
        contact_1: "",
        contact_2: "",
        email: "pharmaciesainteface@gmail.com",
        adresse: "52HQ+M98, RNIE4, Bénin",
        latitude: "7.179158",
        longitude: "2.0384597",
        map_link: "https://maps.google.com/?q=7.179158,2.0384597"
    },
    {
        nom: "PHARMACIE ST LUC DE DJIME",
        photo: "pharmacie-st-luc-djime.jpg",
        ville: "Abomey",
        prefecture: "Zou",
        pays: "Bénin",
        contact_1: "",
        contact_2: "",
        email: "pharmaciestlucdjime@outlook.com",
        adresse: "Abomey, Bénin",
        latitude: "7.1808326",
        longitude: "2.0249666",
        map_link: "https://maps.google.com/?q=7.1808326,2.0249666"
    },
    {
        nom: "Pharmacie Zakpota",
        photo: "pharmacie-zakpota.jpg",
        ville: "Zakpota",
        prefecture: "Zou",
        pays: "Bénin",
        contact_1: "+229 01 57 97 24 08",
        contact_2: "",
        email: "pharmaciezakpota@yahoo.fr",
        adresse: "229, Bénin",
        latitude: "7.2274599",
        longitude: "2.2141601",
        map_link: "https://maps.google.com/?q=7.2274599,2.2141601"
    },
    {
        nom: "Pharmacie Principale De Ketou",
        photo: "pharmacie-principale-ketou.jpg",
        ville: "Kétou",
        prefecture: "Plateau",
        pays: "Bénin",
        contact_1: "",
        contact_2: "",
        email: "pharmacieprincipaleketou@gmail.com",
        adresse: "9J92+53J, Kétou, Bénin",
        latitude: "7.3679546",
        longitude: "2.6001392",
        map_link: "https://maps.google.com/?q=7.3679546,2.6001392"
    },
    {
        nom: "Pharmacie Les Collines",
        photo: "pharmacie-les-collines.jpg",
        ville: "Dassa",
        prefecture: "Collines",
        pays: "Bénin",
        contact_1: "",
        contact_2: "",
        email: "pharmacielescollines@outlook.com",
        adresse: "Dassa, Bénin",
        latitude: "7.7775908",
        longitude: "2.1938646",
        map_link: "https://maps.google.com/?q=7.7775908,2.1938646"
    },
    {
        nom: "PHARMACIES CLEMENT",
        photo: "pharmacie-clement.jpg",
        ville: "Partago",
        prefecture: "Borgou",
        pays: "Bénin",
        contact_1: "+229 01 55 29 27 27",
        contact_2: "",
        email: "pharmacieclement@yahoo.fr",
        adresse: "GWQ2+CQ, Partago, Bénin",
        latitude: "9.5385032",
        longitude: "1.9020363",
        map_link: "https://maps.google.com/?q=9.5385032,1.9020363"
    },
    {
        nom: "Pharmacie Nima",
        photo: "pharmacie-nima.jpg",
        ville: "Parakou",
        prefecture: "Borgou",
        pays: "Bénin",
        contact_1: "",
        contact_2: "",
        email: "pharmacienima@gmail.com",
        adresse: "8JXX+R5M Pharmacie Nima, Parakou, Bénin",
        latitude: "9.3495833",
        longitude: "2.6479233",
        map_link: "https://maps.google.com/?q=9.3495833,2.6479233"
    },
    {
        nom: "Pharmacie Taïfa",
        photo: "pharmacie-taifa.jpg",
        ville: "Djougou",
        prefecture: "Donga",
        pays: "Bénin",
        contact_1: "+229 01 63 63 81 81",
        contact_2: "",
        email: "pharmacietaifa@outlook.com",
        adresse: "MMW7+H45, Djougou, Bénin",
        latitude: "9.6963942",
        longitude: "1.6628648",
        map_link: "https://maps.google.com/?q=9.6963942,1.6628648"
    },
    {
        nom: "Pharmacie Zongo II",
        photo: "pharmacie-zongo-ii.jpg",
        ville: "Parakou",
        prefecture: "Borgou",
        pays: "Bénin",
        contact_1: "",
        contact_2: "",
        email: "pharmaciezongoii@yahoo.fr",
        adresse: "9J8F+3QC, Parakou, Bénin",
        latitude: "9.3651845",
        longitude: "2.6243752",
        map_link: "https://maps.google.com/?q=9.3651845,2.6243752"
    },
    {
        nom: "Pharmacie Copargo",
        photo: "pharmacie-copargo.jpg",
        ville: "Kopargo",
        prefecture: "Atacora",
        pays: "Bénin",
        contact_1: "",
        contact_2: "",
        email: "pharmaciecopargo@gmail.com",
        adresse: "RGMX+WR2, RNIE3, Kopargo, Bénin",
        latitude: "9.834537",
        longitude: "1.5491249",
        map_link: "https://maps.google.com/?q=9.834537,1.5491249"
    },
    {
        nom: "PHARMACIE DU PLATEAU",
        photo: "pharmacie-du-plateau.jpg",
        ville: "Parakou",
        prefecture: "Borgou",
        pays: "Bénin",
        contact_1: "+229 01 64 05 04 05",
        contact_2: "",
        email: "pharmacieduplateau@outlook.com",
        adresse: "Unnamed Road, Parakou, Bénin",
        latitude: "9.3826246",
        longitude: "2.6342682",
        map_link: "https://maps.google.com/?q=9.3826246,2.6342682"
    },
    {
        nom: "Pharmacie de la Cité des KOBOUROU",
        photo: "pharmacie-cite-kobourou.jpg",
        ville: "Parakou",
        prefecture: "Borgou",
        pays: "Bénin",
        contact_1: "+229 01 68 59 42 49",
        contact_2: "",
        email: "pharmaciekobourou@yahoo.fr",
        adresse: "Quartier Sinangourou, non loin du Palais royal, Parakou, Bénin",
        latitude: "9.3299896",
        longitude: "2.621478",
        map_link: "https://maps.google.com/?q=9.3299896,2.621478"
    },
    {
        nom: "Pharmacie Albarika",
        photo: "pharmacie-albarika.jpg",
        ville: "Kandi",
        prefecture: "Alibori",
        pays: "Bénin",
        contact_1: "",
        contact_2: "",
        email: "pharmaciealbarika@gmail.com",
        adresse: "4WMG+3QR, Kandi, Bénin",
        latitude: "11.1327465",
        longitude: "2.9268815",
        map_link: "https://maps.google.com/?q=11.1327465,2.9268815"
    },
    {
        nom: "Pharmacie NA SIARA",
        photo: "pharmacie-na-siara.jpg",
        ville: "Kandi",
        prefecture: "Alibori",
        pays: "Bénin",
        contact_1: "",
        contact_2: "",
        email: "pharmacienasiara@outlook.com",
        adresse: "4WHJ+376, RNIE2, Kandi, Bénin",
        latitude: "11.1276606",
        longitude: "2.9306367",
        map_link: "https://maps.google.com/?q=11.1276606,2.9306367"
    },
    {
        nom: "Pharmacie Camp Guezo",
        photo: "pharmacie-camp-guezo.jpg",
        ville: "Cotonou",
        prefecture: "Littoral",
        pays: "Bénin",
        contact_1: "+229 01 21 31 35 55",
        contact_2: "",
        email: "info@pharmaciecampguezo.net",
        adresse: "Unnamed Road, Cotonou, Bénin",
        latitude: "6.3561453",
        longitude: "2.4182102",
        map_link: "https://maps.google.com/?q=6.3561453,2.4182102"
    },
    {
        nom: "Pharmacie Cristal Santé",
        photo: "pharmacie-cristal-sante.jpg",
        ville: "Cotonou",
        prefecture: "Littoral",
        pays: "Bénin",
        contact_1: "+229 01 94 51 59 29",
        contact_2: "",
        email: "pharmaciecristalsante@outlook.com",
        adresse: "99H3+889, Unnamed Road, Cotonou, Bénin",
        latitude: "6.3782813",
        longitude: "2.3533605",
        map_link: "https://maps.google.com/?q=6.3782813,2.3533605"
    },
    {
        nom: "Pharmacie Agblangandan",
        photo: "pharmacie-agblangandan.jpg",
        ville: "Agblangandan",
        prefecture: "Ouémé",
        pays: "Bénin",
        contact_1: "",
        contact_2: "",
        email: "pharmacieagblangandan@yahoo.fr",
        adresse: "9FGP+4J2, Agblangandan, Bénin",
        latitude: "6.3752735",
        longitude: "2.4865157",
        map_link: "https://maps.google.com/?q=6.3752735,2.4865157"
    },
    {
        nom: "Pharmacie Adjibadé",
        photo: "pharmacie-adjibade.jpg",
        ville: "Porto-Novo",
        prefecture: "Ouémé",
        pays: "Bénin",
        contact_1: "+229 01 57 28 08 96",
        contact_2: "",
        email: "pharmacieadjibade@outlook.com",
        adresse: "FJQF+CVW, Porto-Novo, Bénin",
        latitude: "6.4911696",
        longitude: "2.6254872",
        map_link: "https://maps.google.com/?q=6.4911696,2.6254872"
    },
    {
        nom: "Pharmacie NIMA",
        photo: "pharmacie-nima-cotonou.jpg",
        ville: "Cotonou",
        prefecture: "Littoral",
        pays: "Bénin",
        contact_1: "+229 01 99 26 13 41",
        contact_2: "",
        email: "pharmacienima.cotonou@gmail.com",
        adresse: "Route pavée du port sec en allant vers la bourse du travail 4ème rue à droite, Cotonou, Bénin",
        latitude: "6.3575574",
        longitude: "2.421835",
        map_link: "https://maps.google.com/?q=6.3575574,2.421835"
    },
    {
        nom: "Pharmacie Zongo",
        photo: "pharmacie-zongo-cotonou.jpg",
        ville: "Cotonou",
        prefecture: "Littoral",
        pays: "Bénin",
        contact_1: "",
        contact_2: "",
        email: "pharmaciezongo.cotonou@outlook.com",
        adresse: "06 BP 2630, Cotonou, Bénin",
        latitude: "6.3594453",
        longitude: "2.4257157",
        map_link: "https://maps.google.com/?q=6.3594453,2.4257157"
    },
    {
        nom: "Pharmacie Akassato",
        photo: "pharmacie-akassato.jpg",
        ville: "Allada",
        prefecture: "Atlantique",
        pays: "Bénin",
        contact_1: "+229 01 95 84 69 10",
        contact_2: "",
        email: "pharmacieakassato@yahoo.fr",
        adresse: "RNIE2, Allada, Bénin",
        latitude: "6.5118497",
        longitude: "2.3629098",
        map_link: "https://maps.google.com/?q=6.5118497,2.3629098"
    },
    {
        nom: "Pharmacie Godomey Fignonhou",
        photo: "pharmacie-godomey-fignonhou.jpg",
        ville: "Cotonou",
        prefecture: "Littoral",
        pays: "Bénin",
        contact_1: "+229 01 95 14 48 42",
        contact_2: "",
        email: "pharmaciegodomey@gmail.com",
        adresse: "Unnamed Road, Cotonou, Bénin",
        latitude: "6.3741922",
        longitude: "2.3406945",
        map_link: "https://maps.google.com/?q=6.3741922,2.3406945"
    },
    {
        nom: "Pharmacie Espace Santé",
        photo: "pharmacie-espace-sante.jpg",
        ville: "Cotonou",
        prefecture: "Littoral",
        pays: "Bénin",
        contact_1: "+229 01 67 30 95 51",
        contact_2: "",
        email: "pharmacieespacesante@outlook.com",
        adresse: "Cotonou, Bénin",
        latitude: "6.3833853",
        longitude: "2.3349784",
        map_link: "https://maps.google.com/?q=6.3833853,2.3349784"
    },
    {
        nom: "Pharmacie Luli Luli",
        photo: "pharmacie-luli-luli.jpg",
        ville: "Cotonou",
        prefecture: "Littoral",
        pays: "Bénin",
        contact_1: "",
        contact_2: "",
        email: "pharmacieluliluli@yahoo.fr",
        adresse: "99C4+PPF, Cotonou, Bénin",
        latitude: "6.3718246",
        longitude: "2.356803",
        map_link: "https://maps.google.com/?q=6.3718246,2.356803"
    },
    {
        nom: "Pharmacie Tanto le joker",
        photo: "pharmacie-tanto-joker.jpg",
        ville: "Cotonou",
        prefecture: "Littoral",
        pays: "Bénin",
        contact_1: "+229 01 97 05 66 06",
        contact_2: "",
        email: "pharmacietanto@gmail.com",
        adresse: "Cotonou, Bénin",
        latitude: "6.3713125",
        longitude: "2.4721875",
        map_link: "https://maps.google.com/?q=6.3713125,2.4721875"
    },
    {
        nom: "Pharmacie Océane",
        photo: "pharmacie-oceane.jpg",
        ville: "Cotonou",
        prefecture: "Littoral",
        pays: "Bénin",
        contact_1: "",
        contact_2: "",
        email: "pharmacieoceane@outlook.com",
        adresse: "9947+RX8, Rue 2356, Cotonou, Bénin",
        latitude: "6.3570406",
        longitude: "2.3649561",
        map_link: "https://maps.google.com/?q=6.3570406,2.3649561"
    },
    {
        nom: "Pharmacie Zogbo",
        photo: "pharmacie-zogbo.jpg",
        ville: "Cotonou",
        prefecture: "Littoral",
        pays: "Bénin",
        contact_1: "",
        contact_2: "",
        email: "pharmaciezogbo@yahoo.fr",
        adresse: "Cotonou, Bénin",
        latitude: "6.3901684",
        longitude: "2.3882228",
        map_link: "https://maps.google.com/?q=6.3901684,2.3882228"
    },
    {
        nom: "Pharmacie MAHUENA",
        photo: "pharmacie-mahuena.jpg",
        ville: "Cotonou",
        prefecture: "Littoral",
        pays: "Bénin",
        contact_1: "+229 01 90 15 56 96",
        contact_2: "",
        email: "pharmaciemahuena@gmail.com",
        adresse: "01 Bp 960 Carré 145 Scoa, Cotonou, Bénin",
        latitude: "6.360405",
        longitude: "2.4307522",
        map_link: "https://maps.google.com/?q=6.360405,2.4307522"
    },
    {
        nom: "Pharmacie Atinkanme",
        photo: "pharmacie-atinkanme.jpg",
        ville: "Cotonou",
        prefecture: "Littoral",
        pays: "Bénin",
        contact_1: "+229 01 60 01 97 72",
        contact_2: "",
        email: "pharmacieatinkanme@yahoo.fr",
        adresse: "Boulevard Steinmetz, Cotonou, Bénin",
        latitude: "6.3616264",
        longitude: "2.4343739",
        map_link: "https://maps.google.com/?q=6.3616264,2.4343739"
    },

    // BURKINA FASO
    {
        nom: "Pharmacie Camille",
        photo: "pharmacie-camille.jpg",
        ville: "Ouagadougou",
        prefecture: "Kadiogo",
        pays: "Burkina Faso",
        contact_1: "+226 61 80 14 77",
        contact_2: "",
        email: "pharmaciecamille@outlook.com",
        adresse: "9GGC+8F7, Dassasgo, Ouagadougou, Burkina Faso",
        latitude: "12.3757877",
        longitude: "-1.4788303",
        map_link: "https://maps.google.com/?q=12.3757877,-1.4788303"
    },
    {
        nom: "Pharmacie Balkuy",
        photo: "pharmacie-balkuy.jpg",
        ville: "Ouagadougou",
        prefecture: "Kadiogo",
        pays: "Burkina Faso",
        contact_1: "+226 25 37 51 36",
        contact_2: "",
        email: "pharmaciebalkuy@gmail.com",
        adresse: "8G59+R3H, Ouaga 2000, Ouagadougou, Burkina Faso",
        latitude: "12.3095647",
        longitude: "-1.4822765",
        map_link: "https://maps.google.com/?q=12.3095647,-1.4822765"
    },
    {
        nom: "Pharmacie Zone 1",
        photo: "pharmacie-zone-1.jpg",
        ville: "Ouagadougou",
        prefecture: "Kadiogo",
        pays: "Burkina Faso",
        contact_1: "+226 63 53 26 70",
        contact_2: "",
        email: "pharmaciezone1@yahoo.fr",
        adresse: "9G8H+XF2, Zone I, Ouagadougou, Burkina Faso",
        latitude: "12.366879",
        longitude: "-1.4698935",
        map_link: "https://maps.google.com/?q=12.366879,-1.4698935"
    },
    {
        nom: "Pharmacie Koulouba",
        photo: "pharmacie-koulouba.jpg",
        ville: "Ouagadougou",
        prefecture: "Kadiogo",
        pays: "Burkina Faso",
        contact_1: "+226 25 31 19 18",
        contact_2: "",
        email: "pharmaciekoulouba@outlook.com",
        adresse: "9F8R+M52, Ave Houari Boumedienne, Koulouba, Ouagadougou, Burkina Faso",
        latitude: "12.3666291",
        longitude: "-1.5096143",
        map_link: "https://maps.google.com/?q=12.3666291,-1.5096143"
    },
    {
        nom: "Pharmacie du Sahel",
        photo: "pharmacie-du-sahel.jpg",
        ville: "Ouagadougou",
        prefecture: "Kadiogo",
        pays: "Burkina Faso",
        contact_1: "+226 25 31 81 95",
        contact_2: "",
        email: "pharmaciedusahel@gmail.com",
        adresse: "9F8P+G49, Koulouba, Ouagadougou, Burkina Faso",
        latitude: "12.3662949",
        longitude: "-1.5146408",
        map_link: "https://maps.google.com/?q=12.3662949,-1.5146408"
    },
    {
        nom: "Pharmacie de Pissy",
        photo: "pharmacie-de-pissy.jpg",
        ville: "Ouagadougou",
        prefecture: "Kadiogo",
        pays: "Burkina Faso",
        contact_1: "+226 25 41 40 66",
        contact_2: "",
        email: "pharmaciedepissy@yahoo.fr",
        adresse: "Pissy, Ouagadougou, Burkina Faso",
        latitude: "12.3373385",
        longitude: "-1.5643054",
        map_link: "https://maps.google.com/?q=12.3373385,-1.5643054"
    },
    {
        nom: "Pharmacie de l'Hôpital",
        photo: "pharmacie-de-l-hopital.jpg",
        ville: "Ouagadougou",
        prefecture: "Kadiogo",
        pays: "Burkina Faso",
        contact_1: "+226 25 30 66 41",
        contact_2: "",
        email: "pharmaciehopital@outlook.com",
        adresse: "9FJV+V9F, Avenue du Capitaine Thomas Sankara, Ouagadougou, Burkina Faso",
        latitude: "12.3821996",
        longitude: "-1.5065921",
        map_link: "https://maps.google.com/?q=12.3821996,-1.5065921"
    },
    {
        nom: "Pharmacie du centre",
        photo: "pharmacie-du-centre.jpg",
        ville: "Ouagadougou",
        prefecture: "Kadiogo",
        pays: "Burkina Faso",
        contact_1: "+226 25 31 16 60",
        contact_2: "",
        email: "pharmaciecentre@gmail.com",
        adresse: "570 Av de la Nation, Koulouba, Ouagadougou, Burkina Faso",
        latitude: "12.3701112",
        longitude: "-1.5243046",
        map_link: "https://maps.google.com/?q=12.3701112,-1.5243046"
    },
    {
        nom: "Pharmacie Benaia",
        photo: "pharmacie-benaia.jpg",
        ville: "Ouagadougou",
        prefecture: "Kadiogo",
        pays: "Burkina Faso",
        contact_1: "+226 25 37 28 30",
        contact_2: "",
        email: "pharmaciebenaia@yahoo.fr",
        adresse: "8GXC+X7W, Ouagadougou, Burkina Faso",
        latitude: "12.3499844",
        longitude: "-1.4792868",
        map_link: "https://maps.google.com/?q=12.3499844,-1.4792868"
    },
    {
        nom: "Pharmacie du Centre Médical PROXIMITE",
        photo: "pharmacie-proximite.jpg",
        ville: "Ouagadougou",
        prefecture: "Kadiogo",
        pays: "Burkina Faso",
        contact_1: "+226 70 14 22 14",
        contact_2: "",
        email: "pharmacieproximite@outlook.com",
        adresse: "9C7V+G5R, Goughin, Ouagadougou, Burkina Faso",
        latitude: "12.3638702",
        longitude: "-1.5571088",
        map_link: "https://maps.google.com/?q=12.3638702,-1.5571088"
    },
    {
        nom: "Pharmacie Song-Taaba",
        photo: "pharmacie-song-taaba.jpg",
        ville: "Ouagadougou",
        prefecture: "Kadiogo",
        pays: "Burkina Faso",
        contact_1: "+226 25 48 33 82",
        contact_2: "",
        email: "pharmaciesongtaaba@gmail.com",
        adresse: "9GVR+X23, Dassasgo, Ouagadougou, Burkina Faso",
        latitude: "12.3948954",
        longitude: "-1.4599384",
        map_link: "https://maps.google.com/?q=12.3948954,-1.4599384"
    },
    {
        nom: "Pharmacie Somgandé",
        photo: "pharmacie-somgande.jpg",
        ville: "Ouagadougou",
        prefecture: "Kadiogo",
        pays: "Burkina Faso",
        contact_1: "+226 70 14 39 25",
        contact_2: "",
        email: "pharmaciesomgande@yahoo.fr",
        adresse: "CG46+G4H, Somgandé, Ouagadougou, Burkina Faso",
        latitude: "12.4063012",
        longitude: "-1.4896501",
        map_link: "https://maps.google.com/?q=12.4063012,-1.4896501"
    },
    {
        nom: "Pharmacie Belle Ville",
        photo: "pharmacie-belle-ville.jpg",
        ville: "Ouagadougou",
        prefecture: "Kadiogo",
        pays: "Burkina Faso",
        contact_1: "",
        contact_2: "",
        email: "pharmaciebelleville@outlook.com",
        adresse: "8C5R+3VW, Belle Ville, Ouagadougou, Burkina Faso",
        latitude: "12.307727",
        longitude: "-1.557804",
        map_link: "https://maps.google.com/?q=12.307727,-1.557804"
    },
    {
        nom: "Pharmacie Bethania",
        photo: "pharmacie-bethania.jpg",
        ville: "Ouagadougou",
        prefecture: "Kadiogo",
        pays: "Burkina Faso",
        contact_1: "+226 25 31 31 41",
        contact_2: "",
        email: "pharmaciebethania@gmail.com",
        adresse: "9F78+JG7, Ave Oumarou Kanazoe, Bilbalogho, Ouagadougou, Burkina Faso",
        latitude: "12.3640405",
        longitude: "-1.5336946",
        map_link: "https://maps.google.com/?q=12.3640405,-1.5336946"
    },
    {
        nom: "Pharmacie Principale",
        photo: "pharmacie-principale-ouaga.jpg",
        ville: "Ouagadougou",
        prefecture: "Kadiogo",
        pays: "Burkina Faso",
        contact_1: "+226 25 37 54 15",
        contact_2: "",
        email: "pharmacieprincipale@yahoo.fr",
        adresse: "8F4W+FC4, Ouaga 2000, Ouagadougou, Burkina Faso",
        latitude: "12.3061395",
        longitude: "-1.5039114",
        map_link: "https://maps.google.com/?q=12.3061395,-1.5039114"
    },
    {
        nom: "Pharmacie Hope",
        photo: "pharmacie-hope.jpg",
        ville: "Ouagadougou",
        prefecture: "Kadiogo",
        pays: "Burkina Faso",
        contact_1: "+226 71 14 22 22",
        contact_2: "",
        email: "pharmaciehope@outlook.com",
        adresse: "CH38+P8, Ouagadougou, Burkina Faso",
        latitude: "12.4055655",
        longitude: "-1.4322349",
        map_link: "https://maps.google.com/?q=12.4055655,-1.4322349"
    },
    {
        nom: "Pharmacie du Saint Bernard",
        photo: "pharmacie-saint-bernard.jpg",
        ville: "Ouagadougou",
        prefecture: "Kadiogo",
        pays: "Burkina Faso",
        contact_1: "+226 25 45 14 82",
        contact_2: "",
        email: "pharmaciesaintbernard@gmail.com",
        adresse: "8G66+WF6, Av. Ousmane SEMBENE, Ouaga 2000, Ouagadougou, Burkina Faso",
        latitude: "12.3122831",
        longitude: "-1.4888735",
        map_link: "https://maps.google.com/?q=12.3122831,-1.4888735"
    },
    {
        nom: "Pharmacie Talba",
        photo: "pharmacie-talba.jpg",
        ville: "Ouagadougou",
        prefecture: "Kadiogo",
        pays: "Burkina Faso",
        contact_1: "+226 25 36 22 25",
        contact_2: "",
        email: "pharmacietalba@yahoo.fr",
        adresse: "9GG5+GJ2, Zogona, Ouagadougou, Burkina Faso",
        latitude: "12.3762697",
        longitude: "-1.4909898",
        map_link: "https://maps.google.com/?q=12.3762697,-1.4909898"
    },
    {
        nom: "Pharmacie le Rocher",
        photo: "pharmacie-le-rocher.jpg",
        ville: "Ouagadougou",
        prefecture: "Kadiogo",
        pays: "Burkina Faso",
        contact_1: "+226 70 14 39 32",
        contact_2: "",
        email: "pharmacierocher@outlook.com",
        adresse: "8F9J+3R5, Rue de Saponé, Ouagadougou, Ouagadougou, Burkina Faso",
        latitude: "12.3176492",
        longitude: "-1.5178971",
        map_link: "https://maps.google.com/?q=12.3176492,-1.5178971"
    },
    {
        nom: "Pharmacie de l´Hippodrome Sarl",
        photo: "pharmacie-hippodrome.jpg",
        ville: "Ouagadougou",
        prefecture: "Kadiogo",
        pays: "Burkina Faso",
        contact_1: "+226 25 34 02 32",
        contact_2: "",
        email: "pharmaciehippodrome@gmail.com",
        adresse: "Nonsin, Ouagadougou, Burkina Faso",
        latitude: "12.3756732",
        longitude: "-1.5575485",
        map_link: "https://maps.google.com/?q=12.3756732,-1.5575485"
    }
]
